#ifndef __CFG_EXT_H
#define __CFG_EXT_H

/* FS: Extended.cfg stuff */
extern boolean headBob;
extern int	drawTime; /* FS: Draw Time on Automap */
extern boolean	useIntGus; /* FS: Use internal GUS*.WADs */
extern boolean novert; /* FS: No vertical mouse movement */
extern boolean noprecache;
extern boolean noquitsound;
extern boolean nowipe;
extern boolean usePalFlash;

/* FS: Custom weapon keys */
extern boolean	use_wpnbinds;
extern int	wpn_shotgun;
extern int	wpn_chaingun;
extern int	wpn_rocket;
extern int	wpn_plasma;

#endif
